FROM golang:latest
WORKDIR /
RUN go get -d -v github.com/unioproject/tanglebeat/tbsender
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o tbsender ${GOPATH}/src/github.com/unioproject/tanglebeat/tbsender

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 tbsender .
ENV SITE_DATA_DIR="/root/config"
ENTRYPOINT ["./tbsender"]
