{
 "title": "Tanglebeat demo",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Disclaimer",
   "type": "text",
   "gridPos": { "h": 3, "w": 19, "x": 0, "y": 0 },
   "content": "#### Tangebeat site is a work in progress and any metrics, charts and dashboards you see in it are experimental and may change.\n\n\n"
  },
  {
   "title": "About Tanglebeat",
   "type": "text",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 3 },
   "content": "\n\n**Tanglebeat** is a lightweight software agent intended for collection of Tangle health -related metrics to [Prometheus TSDB](https://prometheus.io). \n\nTangelbeat can run standalone or in distributed configurations to collect metrics from the network. Behind this Grafana dashboard demo there're two Tanglebeat instances\non different nodes running 7 transfer sequences in total . Pratical productions environments as well as dashboard might be different. \nAlso open nanomsg data stream enables extentions of Tanglebeat to provide new metrics and services.\n\nTanglebeat is a successor of [Traveling IOTA](http://traviota.iotalt.com) project. It is open source. \nDetailed description can be found in [GitHub](https://github.com/lunfardo314/tanglebeat) (closed until stabil release)\n"
  },
  {
   "title": "Confirmation time statistics",
   "type": "text",
   "gridPos": { "h": 3, "w": 19, "x": 0, "y": 8 },
   "content": "\n**TfPH** or **Transfers Per Hour** metrics is calculated by running several sequences of IOTA transfers of the whole balance from one address to another. \nUpon confirmation of the transfer Tanglebeat creates new bundle and makes sure it is confirmed by *promoting* and *reattaching* of it (if necessary).\nVarious data is collected in the process and then is scraped by Prometheus as metrics. \n\n**TfPH** is calculated as number of confirmed transfers in one hour *per sequence*. \nIt indicates perceived confirmation speed of the Tangle\": the number of transfers an ideal wallet would be able to make in one hour. \n\n\n**Note** that TfPH calculated by Tanglebeat is significantly higher than the one from [Traveling IOTA](http://traviota.iotalt.com) due to the difference of algorithms as well as different configuration parameters."
  },
  {
   "title": "TfPH - Transfers per hour",
   "type": "graph",
   "description": "kuku",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tanglebeat:confirmation_metrics:tfph_adjusted",
     "legendFormat": "TfPH"
    }
   ]
  },
  {
   "title": "TfPH current",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "tanglebeat:confirmation_metrics:tfph_adjusted"
    }
   ]
  },
  {
   "title": "Average transfer confirmation time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "clamp_max(sum(increase(tanglebeat_confirmation_duration_counter[30m]))/sum(increase(tanglebeat_confirmation_counter[30m])), 1200)",
     "legendFormat": "avg conf time 30 min"
    },
    {
     "expr": "clamp_max(sum(increase(tanglebeat_confirmation_duration_counter[1h]))/sum(increase(tanglebeat_confirmation_counter[1h])), 1200)",
     "legendFormat": "avg conf time 1h"
    }
   ]
  },
  {
   "title": "Confirmation time distribution (by min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(tanglebeat_confirmation_duration_counter[1h])/rate(tanglebeat_confirmation_counter[1h]))/60",
     "legendFormat": "avg conf time 1h"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 23 },
   "content": "**PoW cost per transfer** metrics is equal to the average number of transactions needed to confirm a transfer. \nIt includes not only transactions of the original bundle (usualy 3), but also all promotion transactions and reattachments (if any)\n\nBy promoting and reattaching *Tanglebeat* contributes to the overall **TPS** of the Tangle as slow *value spammer*\n\n_PoW cost_ metrics are experimental. It depends on the promotion startegy. In the current demo it is _promote every 15 sec_. \nIt is unclear how and when transfer confirmation time depends on promotion startegy. \n\nThat might give a ground to compare e.g. BTC transactions (transfers) to IOTA transactions (one transfer costs several transactions).  \n"
  },
  {
   "title": "PoW cost per transfer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tanglebeat_pow_cost_counter[1h]))/sum(increase(tanglebeat_confirmation_counter[1h]))",
     "legendFormat": "pow cost"
    }
   ]
  },
  {
   "title": "Contribution to TPS 1h",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(tanglebeat_pow_cost_counter[1h]))"
    }
   ]
  },
  {
   "title": "Zero MQ -based metrics",
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 35 },
   "content": "Tanglebeat also provides usual *Zero MQ based metrics* such as *TPS*, *CTPS*, *Confirmation rate* and *Seconds between milestones*"
  },
  {
   "title": "TPS vs CTPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tanglebeat_tx_counter_compound[20m])",
     "legendFormat": "TPS avg 20 min avg"
    },
    {
     "expr": "rate(tanglebeat_ctx_counter_compound[20m])",
     "legendFormat": "CTPS avg 20 min avg"
    }
   ]
  },
  {
   "title": "TPS 5 min avg",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 11, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(tanglebeat_tx_counter_compound[5m])"
    }
   ]
  },
  {
   "title": "CTPS 5 min avg",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 11, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(tanglebeat_ctx_counter_compound[5m])"
    }
   ]
  },
  {
   "title": "Confirmation rate %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100* rate(tanglebeat_ctx_counter_compound[20m]) / rate(tanglebeat_tx_counter_compound[20m])",
     "legendFormat": "Conf. rate 20 min avg"
    }
   ]
  },
  {
   "title": "Conf. rate 5 min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 11, "y": 45 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * rate(tanglebeat_ctx_counter_compound[5m]) / rate(tanglebeat_tx_counter_compound[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 49 },
   "content": "Tanglebeat keeps a counter for errors returned by IOTA API calls. It gives idea about the health of the IOTA nodes Tanglebeat is connected to. \nThis and other metrics very much depends on the confirguration of the Tanglebeat.  "
  },
  {
   "title": "IOTA API error count last 10 min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tanglebeat_iota_api_error_counter[10m])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "increase(tanglebeat_iota_api_error_counter{endpoint=\"https://api.powsrv.io:443\"}[10m])",
     "legendFormat": "api.powsrv.io"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 58 },
   "content": "Each sequence of transfers is based on one seed. Sequences is *active* if it has at least one confirmation in 15 minutes. \nTfPH averages are calculated over average number of active sequences in order to minimize effect of technical downtime or changes in the configuration."
  },
  {
   "title": "Number of sequences active last 15 min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tanglebeat:confirmation_metrics:num_active_seq",
     "legendFormat": "number of active sequences"
    },
    {
     "expr": "tanglebeat:confirmation_metrics:avg_seq_num_active",
     "legendFormat": "avg number of active sequences"
    }
   ]
  },
  {
   "title": "Number active sequences",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 61 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "tanglebeat:confirmation_metrics:num_active_seq"
    }
   ]
  }
 ]
}